# Generated by Django 5.0 on 2023-12-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField()),
                ('email', models.CharField()),
                ('imageUrl', models.ImageField(upload_to='image')),
                ('externalUserId', models.CharField()),
                ('bio', models.CharField()),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
            ],
        ),
    ]
