# Generated by Django 5.0 on 2023-12-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updatedAt',
            field=models.DateTimeField(blank=True),
        ),
    ]
