# Generated by Django 5.0 on 2024-02-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_createdat_alter_user_updatedat_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followerId',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='followingId',
        ),
    ]
