# Generated by Django 5.0 on 2024-02-09 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_follow_created_at_follow_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockedId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to='user.user')),
                ('blockerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockedBy', to='user.user')),
            ],
        ),
    ]
