# Generated by Django 5.0 on 2024-02-09 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_block'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('blockerId', 'blockedId')},
        ),
    ]
