# Generated by Django 5.0 on 2024-02-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_block_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
    ]
