# Generated by Django 5.0 on 2024-02-11 09:42

import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_follow_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('name_search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('thumbnailUrl', models.CharField(max_length=255)),
                ('ingressId', models.CharField(db_index=True, max_length=255, unique=True)),
                ('serverUrl', models.CharField(max_length=255)),
                ('streamKey', models.CharField(max_length=255)),
                ('isLive', models.BooleanField(default=False)),
                ('isChatEnabled', models.BooleanField(default=True)),
                ('isChatDelayed', models.BooleanField(default=False)),
                ('isChatFollowersOnly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
