# Generated by Django 5.0 on 2024-02-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='ingressId',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='serverUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='streamKey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='thumbnailUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
