# Generated by Django 5.0 on 2024-02-11 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_stream_ingressid_alter_stream_serverurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', unique=True),
        ),
    ]
